"""
utils/crm.py — per-account CRM/growth analytics events and segmentation.

Deliberately separate from metrics.py: that module is an intentionally
anonymous store (one-way-hashed session ids, tested to never leak an email —
see test_metrics.py), built and documented as such in CLAUDE.md. This module
is the opposite by design — every row is plaintext-account-identified,
because segmenting accounts into Trial/Active-Free/Professional/Agency/
Churn-risk and flagging Agency-ready accounts requires knowing which account
did what. Do not add plaintext account data to metrics.py, and do not route
this module's writes through metrics.log_event()/_metrics_session_id().

Also deliberately separate from utils/audits.py's AccessLog/access_log:
that table is a permanent security-audit trail scoped to a handful of
data-access actions (save_audit, delete_audit, etc.) and is explicitly
excluded from the account-deletion purge flow. crm_events is high-volume
growth/marketing data (every audit run, every upgrade prompt shown, every
WhatsApp click) that should be purgeable on an "erase my history" request —
see purge_account_crm_events(), wired into the same flow as
utils.audits.purge_account_audit_content().

Connects directly to the same Postgres database as utils/audits.py, via the
same SUPABASE_DB_URL secret and SQLAlchemy engine pattern (schema lives in
supabase/migrations/0012, mapped here, not generated by this file). All
functions degrade gracefully on DB failure — never crash the app, never
propagate an exception to the caller — matching every other utils/*.py
module's convention.
"""
from __future__ import annotations
import os
from datetime import datetime, timedelta, timezone

from sqlalchemy import Column, BigInteger, Integer, Text, DateTime, JSON, func
from sqlalchemy.orm import declarative_base, Session

Base = declarative_base()

# Same SQLite/rowid-alias autoincrement compat trick as utils/audits.py's
# _PK -- BigInteger alone doesn't qualify as SQLite's "INTEGER PRIMARY KEY"
# rowid alias, which the in-memory test engine needs for working autoincrement.
_PK = BigInteger().with_variant(Integer, "sqlite")

ALLOWED_EVENT_TYPES = {
    "signup", "audit_run", "framework_used", "tier_change",
    "upgrade_prompt_shown", "upgrade_prompt_clicked", "whatsapp_click",
}  # closed set, mirrors metrics.py's EVENT_TYPES allowlist pattern -- a
   # typo'd event_type is silently dropped rather than polluting the
   # dashboard with an unrecognized bucket.

CHURN_WINDOW_DAYS = 30
AGENCY_READY_WINDOW_DAYS = 30


class CrmEvent(Base):
    __tablename__ = "crm_events"
    id = Column(_PK, primary_key=True)
    email = Column(Text, nullable=False)
    event_type = Column(Text, nullable=False)
    # The ORM attribute can't be named `metadata` -- that name is reserved by
    # SQLAlchemy's declarative Base (Base.metadata is the schema registry).
    # Map the Python attribute to the real `metadata` SQL column explicitly.
    metadata_json = Column("metadata", JSON)
    created_at = Column(DateTime(timezone=True), server_default=func.now())


_engine = None


def _get_engine():
    # Identical pattern to utils.audits._get_engine() -- same SUPABASE_DB_URL
    # secret, same cached module global, same "return None, never raise."
    global _engine
    if _engine is not None:
        return _engine
    try:
        import streamlit as st
        db_url = st.secrets.get("SUPABASE_DB_URL") or os.environ.get("SUPABASE_DB_URL", "")
    except Exception:
        db_url = os.environ.get("SUPABASE_DB_URL", "")
    if not db_url:
        return None
    try:
        from sqlalchemy import create_engine
        _engine = create_engine(db_url, pool_pre_ping=True)
    except Exception:
        _engine = None
    return _engine


# ---------------------------------------------------------------------------
# Event logging
# ---------------------------------------------------------------------------

def log_event(email: str, event_type: str, metadata: dict | None = None) -> None:
    """Best-effort, insert-only. Never raises -- a logging failure must not
    block the action it's recording (same contract as utils.audits.log_access).
    Silently no-ops on an unrecognized event_type rather than raising, so a
    typo at a call site degrades to "missing data point," not a crash."""
    if not email or event_type not in ALLOWED_EVENT_TYPES:
        return
    engine = _get_engine()
    if not engine:
        return
    try:
        with Session(engine) as session:
            session.add(CrmEvent(email=email, event_type=event_type, metadata_json=metadata or {}))
            session.commit()
    except Exception:
        pass


def log_audit_run(email: str, donor: str = "") -> None:
    """Convenience wrapper for the 3 audit-run call sites in app.py (single
    result check, Audit My Report, CSV/Excel portfolio upload): emits
    'audit_run' always, plus 'framework_used' if donor is a real, non-
    placeholder value -- so each call site only needs one call instead of two."""
    log_event(email, "audit_run")
    if donor and donor not in ("", "(No donor specified)", "Not specified"):
        log_event(email, "framework_used", metadata={"donor": donor})


# ---------------------------------------------------------------------------
# Segmentation
# ---------------------------------------------------------------------------

def _last_active_by_email() -> dict[str, datetime]:
    """MAX(created_at) per email across ALL crm_events -- deliberately NOT
    sessions.last_seen_at, which refreshes on any page load even without a
    meaningful action. crm_events only has rows for actual logged actions, so
    it's a true activity signal for churn-risk purposes."""
    engine = _get_engine()
    if not engine:
        return {}
    try:
        with Session(engine) as session:
            rows = (session.query(CrmEvent.email, func.max(CrmEvent.created_at))
                    .group_by(CrmEvent.email).all())
            return {email: ts for email, ts in rows}
    except Exception:
        return {}


def agency_ready_emails(window_days: int = AGENCY_READY_WINDOW_DAYS) -> set[str]:
    """Accounts using 2+ distinct donor frameworks, OR running 3+ audits,
    within a rolling window -- computed from crm_events directly (not the
    opt-in-only utils.audits.audits table), so it doesn't blindly miss the
    majority of usage that never opts into saving audit history."""
    engine = _get_engine()
    if not engine:
        return set()
    cutoff = datetime.now(timezone.utc) - timedelta(days=window_days)
    try:
        with Session(engine) as session:
            heavy = (session.query(CrmEvent.email)
                     .filter(CrmEvent.event_type == "audit_run", CrmEvent.created_at >= cutoff)
                     .group_by(CrmEvent.email)
                     .having(func.count(CrmEvent.id) >= 3)
                     .all())
            multi = (session.query(CrmEvent.email)
                     .filter(CrmEvent.event_type == "framework_used", CrmEvent.created_at >= cutoff)
                     .group_by(CrmEvent.email)
                     .having(func.count(func.distinct(CrmEvent.metadata_json["donor"])) >= 2)
                     .all())
            return {r[0] for r in heavy} | {r[0] for r in multi}
    except Exception:
        return set()


def build_segments() -> dict[str, list[dict]]:
    """Returns {"Churn-risk": [...], "Trial": [...], "Active-Free": [...],
    "Professional": [...], "Agency": [...]} -- mutually exclusive buckets,
    computed in that priority order (churn-risk first, across any tier).
    Each row also carries an "agency_ready" boolean (cross-cutting, not a
    6th bucket -- a Professional or Active-Free account can independently
    qualify)."""
    from utils.db import list_all_users
    from utils.metering import FREE_CHECKS_LIMIT

    users = list_all_users()
    last_active = _last_active_by_email()
    ready = agency_ready_emails()
    now = datetime.now(timezone.utc)
    segments: dict[str, list[dict]] = {
        "Churn-risk": [], "Trial": [], "Active-Free": [], "Professional": [], "Agency": [],
    }
    for u in users:
        email = (u.get("email") or "").strip().lower()
        if not email:
            continue
        la = last_active.get(email)
        # SQLite (the in-memory test engine) doesn't preserve tzinfo the way
        # real Postgres does, even on a timezone(True) column -- normalize to
        # UTC so the subtraction below never raises on a naive/aware mismatch.
        if la is not None and la.tzinfo is None:
            la = la.replace(tzinfo=timezone.utc)
        row = {
            "email": email,
            "plan": u.get("plan"),
            "free_checks_used": u.get("free_checks_used"),
            "created_at": u.get("created_at"),
            "last_active_at": la,
            "agency_ready": email in ready,
        }
        # No crm_events row at all (la is None) counts as churned, not
        # "unknown" -- covers accounts created before this table existed and
        # accounts that signed up but never took one logged action.
        if la is None or (now - la).days >= CHURN_WINDOW_DAYS:
            segments["Churn-risk"].append(row)
            continue
        plan = (u.get("plan") or "free").lower()
        if plan == "agency":
            segments["Agency"].append(row)
        elif plan == "professional":
            segments["Professional"].append(row)
        elif (u.get("free_checks_used") or 0) < FREE_CHECKS_LIMIT:
            segments["Trial"].append(row)
        else:
            segments["Active-Free"].append(row)
    return segments


# ---------------------------------------------------------------------------
# Data deletion ("erase my history")
# ---------------------------------------------------------------------------

def purge_account_crm_events(email: str) -> int:
    """Deletes every crm_events row for email. Wired into the same "erase my
    history" flow as utils.audits.purge_account_audit_content() -- unlike
    access_log, this table is marketing/growth data, not a permanent
    compliance trail, so it's in scope for deletion on request."""
    if not email:
        return 0
    engine = _get_engine()
    if not engine:
        return 0
    try:
        with Session(engine) as session:
            n = session.query(CrmEvent).filter(CrmEvent.email == email).delete()
            session.commit()
            return n
    except Exception:
        return 0
