"""
utils/crm.py — per-account CRM/growth analytics events and segmentation.

Deliberately separate from metrics.py: that module is an intentionally
anonymous store (one-way-hashed session ids, tested to never leak an email —
see test_metrics.py), built and documented as such in CLAUDE.md. This module
is the opposite by design — every row is plaintext-account-identified,
because segmenting accounts into Trial/Active-Free/Professional/Agency/
Churn-risk and flagging Agency-ready accounts requires knowing which account
did what. Do not add plaintext account data to metrics.py, and do not route
this module's writes through metrics.log_event()/_metrics_session_id().

Also deliberately separate from utils/audits.py's AccessLog/access_log:
that table is a permanent security-audit trail scoped to a handful of
data-access actions (save_audit, delete_audit, etc.) and is explicitly
excluded from the account-deletion purge flow. crm_events is high-volume
growth/marketing data (every audit run, every upgrade prompt shown, every
WhatsApp click) that should be purgeable on an "erase my history" request —
see purge_account_crm_events(), wired into the same flow as
utils.audits.purge_account_audit_content().

Connects directly to the same Postgres database as utils/audits.py, via the
same SUPABASE_DB_URL secret and SQLAlchemy engine pattern (schema lives in
supabase/migrations/0012, mapped here, not generated by this file). All
functions degrade gracefully on DB failure — never crash the app, never
propagate an exception to the caller — matching every other utils/*.py
module's convention.
"""
from __future__ import annotations
import os
from datetime import datetime, timedelta, timezone

from sqlalchemy import Column, BigInteger, Integer, Text, DateTime, JSON, func
from sqlalchemy.orm import declarative_base, Session

Base = declarative_base()

# Same SQLite/rowid-alias autoincrement compat trick as utils/audits.py's
# _PK -- BigInteger alone doesn't qualify as SQLite's "INTEGER PRIMARY KEY"
# rowid alias, which the in-memory test engine needs for working autoincrement.
_PK = BigInteger().with_variant(Integer, "sqlite")

ALLOWED_EVENT_TYPES = {
    "signup", "audit_run", "framework_used", "tier_change",
    "upgrade_prompt_shown", "upgrade_prompt_clicked", "whatsapp_click",
    "revision_run",
}  # closed set, mirrors metrics.py's EVENT_TYPES allowlist pattern -- a
   # typo'd event_type is silently dropped rather than polluting the
   # dashboard with an unrecognized bucket.
   # "revision_run" (Laudon Ch.9, C1/C2): fired when a user re-scores the
   # same result_statement in-session (app.py's existing _is_rescore flag,
   # previously only used to skip double-charging) -- the strongest
   # retention signal the "embedded" behavioural segment relies on.

CHURN_WINDOW_DAYS = 30
AGENCY_READY_WINDOW_DAYS = 30

# Laudon Ch.9, C2/C3 -- behavioural segmentation and churn thresholds,
# config not constants sprinkled through logic, so they can be tuned without
# hunting through compute_behavioral_segment()'s body.
BEHAVIORAL_SEGMENT_THRESHOLDS = {
    "trial_max_assessments": 2,
    "embedded_min_assessments_30d": 4,
    "org_emergent_min_domain_users": 2,
    "org_emergent_min_donors_30d": 3,
    "lapsed_days": 365,
}
MIN_CHURN_SAMPLE = 10  # same near-empty-sample safeguard as MIN_BENCHMARK_SAMPLE/MIN_BAND_SAMPLE elsewhere
_REVENUE_PLAN_TIERS = {"monthly", "annual", "agency", "professional"}


class CrmEvent(Base):
    __tablename__ = "crm_events"
    id = Column(_PK, primary_key=True)
    email = Column(Text, nullable=False)
    event_type = Column(Text, nullable=False)
    # The ORM attribute can't be named `metadata` -- that name is reserved by
    # SQLAlchemy's declarative Base (Base.metadata is the schema registry).
    # Map the Python attribute to the real `metadata` SQL column explicitly.
    metadata_json = Column("metadata", JSON)
    created_at = Column(DateTime(timezone=True), server_default=func.now())


class CustomerSegmentHistory(Base):
    __tablename__ = "customer_segment_history"
    id = Column(_PK, primary_key=True)
    email = Column(Text, nullable=False)
    segment = Column(Text, nullable=False)
    computed_at = Column(DateTime(timezone=True), server_default=func.now())


class _PaymentRow(Base):
    """Read-only, partial mapping of the `payments` table (utils/db.py's
    get_payment_history() reads the same table via the Supabase REST client
    for the billing page -- this is a separate, minimal SQLAlchemy overlay
    for compute_revenue_churn_rate()'s aggregate query, not a second write
    path). Only the columns this module actually queries are declared."""
    __tablename__ = "payments"
    id = Column(_PK, primary_key=True)
    email = Column(Text, nullable=False)
    plan = Column(Text)
    status = Column(Text)
    created_at = Column(DateTime(timezone=True))


_engine = None


def _get_engine():
    # Identical pattern to utils.audits._get_engine() -- same SUPABASE_DB_URL
    # secret, same cached module global, same "return None, never raise."
    global _engine
    if _engine is not None:
        return _engine
    try:
        import streamlit as st
        db_url = st.secrets.get("SUPABASE_DB_URL") or os.environ.get("SUPABASE_DB_URL", "")
    except Exception:
        db_url = os.environ.get("SUPABASE_DB_URL", "")
    if not db_url:
        return None
    try:
        from sqlalchemy import create_engine
        _engine = create_engine(db_url, pool_pre_ping=True)
    except Exception:
        _engine = None
    return _engine


# ---------------------------------------------------------------------------
# Event logging
# ---------------------------------------------------------------------------

def log_event(email: str, event_type: str, metadata: dict | None = None) -> None:
    """Best-effort, insert-only. Never raises -- a logging failure must not
    block the action it's recording (same contract as utils.audits.log_access).
    Silently no-ops on an unrecognized event_type rather than raising, so a
    typo at a call site degrades to "missing data point," not a crash."""
    if not email or event_type not in ALLOWED_EVENT_TYPES:
        return
    engine = _get_engine()
    if not engine:
        return
    try:
        with Session(engine) as session:
            session.add(CrmEvent(email=email, event_type=event_type, metadata_json=metadata or {}))
            session.commit()
    except Exception:
        pass


def log_audit_run(email: str, donor: str = "") -> None:
    """Convenience wrapper for the 3 audit-run call sites in app.py (single
    result check, Audit My Report, CSV/Excel portfolio upload): emits
    'audit_run' always, plus 'framework_used' if donor is a real, non-
    placeholder value -- so each call site only needs one call instead of two."""
    log_event(email, "audit_run")
    if donor and donor not in ("", "(No donor specified)", "Not specified"):
        log_event(email, "framework_used", metadata={"donor": donor})


# ---------------------------------------------------------------------------
# Segmentation
# ---------------------------------------------------------------------------

def _last_active_by_email() -> dict[str, datetime]:
    """MAX(created_at) per email across ALL crm_events -- deliberately NOT
    sessions.last_seen_at, which refreshes on any page load even without a
    meaningful action. crm_events only has rows for actual logged actions, so
    it's a true activity signal for churn-risk purposes."""
    engine = _get_engine()
    if not engine:
        return {}
    try:
        with Session(engine) as session:
            rows = (session.query(CrmEvent.email, func.max(CrmEvent.created_at))
                    .group_by(CrmEvent.email).all())
            return {email: ts for email, ts in rows}
    except Exception:
        return {}


def agency_ready_emails(window_days: int = AGENCY_READY_WINDOW_DAYS) -> set[str]:
    """Accounts using 2+ distinct donor frameworks, OR running 3+ audits,
    within a rolling window -- computed from crm_events directly (not the
    opt-in-only utils.audits.audits table), so it doesn't blindly miss the
    majority of usage that never opts into saving audit history."""
    engine = _get_engine()
    if not engine:
        return set()
    cutoff = datetime.now(timezone.utc) - timedelta(days=window_days)
    try:
        with Session(engine) as session:
            heavy = (session.query(CrmEvent.email)
                     .filter(CrmEvent.event_type == "audit_run", CrmEvent.created_at >= cutoff)
                     .group_by(CrmEvent.email)
                     .having(func.count(CrmEvent.id) >= 3)
                     .all())
            multi = (session.query(CrmEvent.email)
                     .filter(CrmEvent.event_type == "framework_used", CrmEvent.created_at >= cutoff)
                     .group_by(CrmEvent.email)
                     .having(func.count(func.distinct(CrmEvent.metadata_json["donor"])) >= 2)
                     .all())
            return {r[0] for r in heavy} | {r[0] for r in multi}
    except Exception:
        return set()


def build_segments() -> dict[str, list[dict]]:
    """Returns {"Churn-risk": [...], "Trial": [...], "Active-Free": [...],
    "Professional": [...], "Agency": [...]} -- mutually exclusive buckets,
    computed in that priority order (churn-risk first, across any tier).
    Each row also carries an "agency_ready" boolean (cross-cutting, not a
    6th bucket -- a Professional or Active-Free account can independently
    qualify)."""
    from utils.db import list_all_users
    from utils.metering import FREE_CHECKS_LIMIT

    users = list_all_users()
    last_active = _last_active_by_email()
    ready = agency_ready_emails()
    now = datetime.now(timezone.utc)
    segments: dict[str, list[dict]] = {
        "Churn-risk": [], "Trial": [], "Active-Free": [], "Professional": [], "Agency": [],
    }
    for u in users:
        email = (u.get("email") or "").strip().lower()
        if not email:
            continue
        la = last_active.get(email)
        # SQLite (the in-memory test engine) doesn't preserve tzinfo the way
        # real Postgres does, even on a timezone(True) column -- normalize to
        # UTC so the subtraction below never raises on a naive/aware mismatch.
        if la is not None and la.tzinfo is None:
            la = la.replace(tzinfo=timezone.utc)
        row = {
            "email": email,
            "plan": u.get("plan"),
            "free_checks_used": u.get("free_checks_used"),
            "created_at": u.get("created_at"),
            "last_active_at": la,
            "agency_ready": email in ready,
        }
        # No crm_events row at all (la is None) counts as churned, not
        # "unknown" -- covers accounts created before this table existed and
        # accounts that signed up but never took one logged action.
        if la is None or (now - la).days >= CHURN_WINDOW_DAYS:
            segments["Churn-risk"].append(row)
            continue
        plan = (u.get("plan") or "free").lower()
        if plan == "agency":
            segments["Agency"].append(row)
        elif plan == "professional":
            segments["Professional"].append(row)
        elif (u.get("free_checks_used") or 0) < FREE_CHECKS_LIMIT:
            segments["Trial"].append(row)
        else:
            segments["Active-Free"].append(row)
    return segments


# ---------------------------------------------------------------------------
# Behavioural segmentation (Laudon Ch.9, C2)
#
# Deliberately a SEPARATE function from build_segments() above, not a
# replacement -- build_segments() answers "what tier does this account pay
# for" (used today by _render_admin_crm_segments()); this answers "is this
# account actually using the product, and is that use healthy." The two
# share no algorithm, so this isn't duplicated segmentation logic, just a
# different question asked of the same underlying accounts.
# ---------------------------------------------------------------------------

def compute_behavioral_segment(profile: dict, mel_calendar: dict | None = None, now: datetime | None = None) -> str:
    """Pure function: one customer_profiles row in, one segment name out.
    Precedence (a profile can only ever match its first qualifying check,
    top to bottom -- adjust here if the ordering should change):
      lapsed > at_risk > dormant_seasonal > org_emergent > embedded > episodic > trial

    dormant_seasonal vs. at_risk (the two hardest to tell apart): dormant_seasonal
    is currently OUTSIDE an expected reporting window and was active in this
    same off-season slot last cycle (an expected, non-urgent lull); at_risk is
    currently INSIDE an expected reporting window and quiet despite having
    history -- the donor deadline is now and they're not here."""
    from utils.mel_calendar import is_reporting_month

    now = now or datetime.now(timezone.utc)
    t = BEHAVIORAL_SEGMENT_THRESHOLDS

    touch = profile.get("last_active_at") or profile.get("signup_at")
    if touch is not None and touch.tzinfo is None:
        touch = touch.replace(tzinfo=timezone.utc)
    if touch is None:
        return "trial"
    days_since_touch = (now - touch).days

    total_assessments = profile.get("total_assessments") or 0
    assessments_30d = profile.get("assessments_last_30d") or 0
    revisions_30d = profile.get("revision_count_last_30d") or 0
    domain_users = profile.get("domain_user_count") or 1
    donors_30d = profile.get("distinct_donor_count_30d") or 0
    active_last_cycle = bool(profile.get("active_in_equivalent_window_last_cycle"))

    if days_since_touch >= t["lapsed_days"]:
        return "lapsed"

    currently_reporting = is_reporting_month(now.month, mel_calendar)
    if currently_reporting and days_since_touch > CHURN_WINDOW_DAYS and total_assessments >= 2:
        return "at_risk"

    if not currently_reporting and days_since_touch > CHURN_WINDOW_DAYS and active_last_cycle:
        return "dormant_seasonal"

    if domain_users >= t["org_emergent_min_domain_users"] or donors_30d >= t["org_emergent_min_donors_30d"]:
        return "org_emergent"

    if assessments_30d >= t["embedded_min_assessments_30d"] or revisions_30d >= 1:
        return "embedded"

    if total_assessments < t["trial_max_assessments"]:
        return "trial"

    return "episodic"


def build_behavioral_segments() -> dict[str, list[dict]]:
    """Returns {"trial": [...], "episodic": [...], "embedded": [...],
    "org_emergent": [...], "dormant_seasonal": [...], "at_risk": [...],
    "lapsed": [...]} -- mutually exclusive buckets over every materialized
    customer_profiles row (utils.customer_profiles.list_customer_profiles(),
    itself just a read over the table refresh_customer_profiles() maintains
    -- this function never re-derives touch-point data itself)."""
    from utils.customer_profiles import list_customer_profiles
    from utils.mel_calendar import load_mel_calendar

    calendar = load_mel_calendar()
    now = datetime.now(timezone.utc)
    segments: dict[str, list[dict]] = {
        "trial": [], "episodic": [], "embedded": [], "org_emergent": [],
        "dormant_seasonal": [], "at_risk": [], "lapsed": [],
    }
    for profile in list_customer_profiles():
        segment = compute_behavioral_segment(profile, calendar, now)
        segments.setdefault(segment, []).append(profile)
    return segments


def record_segment_transition(email: str, segment: str) -> None:
    """Inserts a customer_segment_history row only when `segment` differs
    from that account's most recently recorded segment -- a transition log,
    not a per-computation log (the prompt: "the transition matrix is more
    informative than the snapshot"). Never raises."""
    if not email or not segment:
        return
    engine = _get_engine()
    if not engine:
        return
    try:
        with Session(engine) as session:
            # Tiebreak on id (insertion order) -- SQLite's CURRENT_TIMESTAMP
            # (what func.now() compiles to there) only has second resolution,
            # so two rapid inserts can share a computed_at value.
            last = (session.query(CustomerSegmentHistory)
                    .filter(CustomerSegmentHistory.email == email)
                    .order_by(CustomerSegmentHistory.computed_at.desc(), CustomerSegmentHistory.id.desc())
                    .first())
            if last is not None and last.segment == segment:
                return
            session.add(CustomerSegmentHistory(email=email, segment=segment))
            session.commit()
    except Exception:
        pass


def list_segment_history(email: str) -> list[dict]:
    if not email:
        return []
    engine = _get_engine()
    if not engine:
        return []
    try:
        with Session(engine) as session:
            rows = (session.query(CustomerSegmentHistory)
                    .filter(CustomerSegmentHistory.email == email)
                    .order_by(CustomerSegmentHistory.computed_at.desc(), CustomerSegmentHistory.id.desc())
                    .all())
            return [{"email": r.email, "segment": r.segment, "computed_at": r.computed_at} for r in rows]
    except Exception:
        return []


# ---------------------------------------------------------------------------
# Churn, MEL-calendar aware (Laudon Ch.9, C3)
# ---------------------------------------------------------------------------

def compute_behavioral_churn_rate(cohort_month: int | None = None) -> float | None:
    """Numerator: profiles currently at_risk or lapsed. Denominator: profiles
    with any real history (total_assessments > 0) -- a brand-new trial isn't
    part of the churn cohort at all. Optionally restricted to accounts whose
    last touch (or signup, if never active) fell in `cohort_month` (1-12),
    across any year. Returns None below MIN_CHURN_SAMPLE rather than a rate
    computed from a near-empty cohort."""
    from utils.customer_profiles import list_customer_profiles
    from utils.mel_calendar import load_mel_calendar

    calendar = load_mel_calendar()
    now = datetime.now(timezone.utc)
    profiles = [p for p in list_customer_profiles() if (p.get("total_assessments") or 0) > 0]
    if cohort_month is not None:
        def _in_cohort(p):
            t = p.get("last_active_at") or p.get("signup_at")
            return bool(t) and t.month == cohort_month
        profiles = [p for p in profiles if _in_cohort(p)]
    if len(profiles) < MIN_CHURN_SAMPLE:
        return None
    churned = sum(1 for p in profiles if compute_behavioral_segment(p, calendar, now) in ("at_risk", "lapsed"))
    return round(churned / len(profiles), 4)


def compute_revenue_churn_rate() -> float | None:
    """A customer downgrading from a subscription (monthly/annual/agency) to
    occasional pay-per-use is revenue churn without necessarily being
    customer churn -- derived entirely from existing `payments` history
    (no new instrumentation): for every account that ever had a successful
    subscription-tier payment, is their MOST RECENT successful payment's
    plan still a subscription tier? Returns None below MIN_CHURN_SAMPLE."""
    engine = _get_engine()
    if not engine:
        return None
    try:
        with Session(engine) as session:
            rows = (session.query(_PaymentRow.email, _PaymentRow.plan)
                    .filter(_PaymentRow.status == "success")
                    .order_by(_PaymentRow.email, _PaymentRow.created_at.asc())
                    .all())
    except Exception:
        return None
    ever_subscribed: set[str] = set()
    most_recent_plan: dict[str, str] = {}
    for email, plan in rows:
        plan_l = (plan or "").lower()
        if plan_l in _REVENUE_PLAN_TIERS:
            ever_subscribed.add(email)
        most_recent_plan[email] = plan_l
    if len(ever_subscribed) < MIN_CHURN_SAMPLE:
        return None
    downgraded = sum(1 for e in ever_subscribed if most_recent_plan.get(e) not in _REVENUE_PLAN_TIERS)
    return round(downgraded / len(ever_subscribed), 4)


def time_to_second_assessment(email: str) -> int | None:
    """Days between an account's first and second audit_run event -- the
    leading retention indicator this early (it will predict retention
    better than anything else measurable at this data volume). None if the
    account has fewer than 2 audit_run events, or on any DB failure."""
    if not email:
        return None
    engine = _get_engine()
    if not engine:
        return None
    try:
        with Session(engine) as session:
            rows = (session.query(CrmEvent.created_at)
                    .filter(CrmEvent.email == email, CrmEvent.event_type == "audit_run")
                    .order_by(CrmEvent.created_at.asc())
                    .limit(2)
                    .all())
    except Exception:
        return None
    if len(rows) < 2:
        return None
    return (rows[1][0] - rows[0][0]).days


def time_to_second_assessment_distribution() -> list[int]:
    """Bulk version of time_to_second_assessment() across every account with
    2+ audit_run events -- one query, not N+1."""
    engine = _get_engine()
    if not engine:
        return []
    try:
        with Session(engine) as session:
            rows = (session.query(CrmEvent.email, CrmEvent.created_at)
                    .filter(CrmEvent.event_type == "audit_run")
                    .order_by(CrmEvent.email, CrmEvent.created_at.asc())
                    .all())
    except Exception:
        return []
    first_seen: dict[str, datetime] = {}
    seen_second: set = set()
    result: list[int] = []
    for email, created_at in rows:
        if email not in first_seen:
            first_seen[email] = created_at
        elif email not in seen_second:
            result.append((created_at - first_seen[email]).days)
            seen_second.add(email)
    return result


# ---------------------------------------------------------------------------
# Data deletion ("erase my history")
# ---------------------------------------------------------------------------

def purge_account_crm_events(email: str) -> int:
    """Deletes every crm_events row for email. Wired into the same "erase my
    history" flow as utils.audits.purge_account_audit_content() -- unlike
    access_log, this table is marketing/growth data, not a permanent
    compliance trail, so it's in scope for deletion on request."""
    if not email:
        return 0
    engine = _get_engine()
    if not engine:
        return 0
    try:
        with Session(engine) as session:
            n = session.query(CrmEvent).filter(CrmEvent.email == email).delete()
            session.commit()
            return n
    except Exception:
        return 0
