-- 0018_flutterwave_and_currency_fields.sql
-- Multi-currency pricing/ROI internationalization. The Paystack merchant
-- account is Ghana-only (GHS), so real charges in NGN/KES/ZAR are never
-- attempted -- those three fall back to a GHS charge at checkout, shown
-- with a converted-price disclaimer. USD/GBP/EUR route to Flutterwave
-- instead (Stripe was the original choice, but Stripe requires the
-- merchant business to be incorporated in one of its supported countries,
-- which does not include Ghana; Flutterwave supports Ghana-registered
-- businesses directly).
--
-- No customer/subscription id columns are needed for Flutterwave the way
-- Stripe would have used them -- subscription status lookups and
-- cancellation both key off the account's email directly (see
-- utils/flutterwave_payments.py), so there's nothing processor-specific
-- to persist here beyond the currency fields below.
--
-- preferred_currency persists a signed-in user's currency choice across
-- devices/sessions (session_state/query-param alone don't survive a
-- device switch). payments.currency (0004_payments.sql) already exists
-- and keeps recording what was ACTUALLY charged (always GHS for the
-- Paystack path, real currency for the Flutterwave path); the new
-- displayed_currency records what the user was BROWSING in at purchase
-- time -- the two differ for NGN/KES/ZAR GHS-fallback charges.
alter table users add column if not exists preferred_currency text;
alter table payments add column if not exists displayed_currency text;
